version: "3.8"
services:
  server:
    build:
      context: ./api
      dockerfile: Dockerfile       
    ports: ["5000:5000"]
    volumes: ["./api:/usr/src/app/api", "/usr/src/app/api/node_modules"]       
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports: ["3000:3000"]
    volumes: ["/app/node_modules", "./:/app"]
